# Generated by Django 5.1.6 on 2025-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_customuser_user_type_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='studentmail@email.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='studentuser', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'STAFF'), (3, 'ALUMNI'), (4, 'STUDENT')], default=4, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
    ]
