# Generated by Django 5.1.6 on 2026-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_committeemember_membershippayment_subject_alumni_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='sheet_row_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='membershippayment',
            unique_together={('member_type', 'sheet_row_id')},
        ),
    ]
